version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - bencodezen
  labels:
  - dependencies
  ignore:
  - dependency-name: textlint
    versions:
    - 11.8.2
    - 11.8.3
  - dependency-name: lerna
    versions:
    - 3.22.1
  - dependency-name: "@vue/test-utils"
    versions:
    - 1.1.3
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
